### ISSUE TITLE
Any Release Notes?

### ISSUE THREAD

**Issue by amit1rrr** [diff-match-patch-python/diff-match-patch#2]
I'm currently on version 20121119 and I [can see that there 2 more versions released](https://pypi.org/project/diff-match-patch/20181111/#history) after this. 

I'm wondering if the updated library has any performance related improvements. If yes, I'd love to upgrade (assuming no breaking change). In general, are there release notes somewhere? Apologies if I missed the notes (couldn't find them on GitHub & PyPI).

**Comment by amyreese** [comment]
Sorry for missing this. There have been no real changes to actual code other than formatting and fixing deprecations. The original upstream project hasn't changed in over five years. This project is mostly about maintaining a modern, tested release, with the intent to pull upstream changes if/when they happen in the future.

There is now a [changelog](https://github.com/diff-match-patch-python/diff-match-patch/blob/main/CHANGELOG.md) that covers changes since I took over project maintenance, but I don't have info/time to compile change information from before that period.
